# Generated by Django 2.2.6 on 2019-12-27 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cine', '0002_auto_20191227_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcion',
            options={'verbose_name_plural': 'Funciones'},
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_boletas', models.PositiveIntegerField()),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Funcion')),
                ('usuario', models.OneToOneField(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
