# Generated by Django 2.2.6 on 2019-12-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0004_auto_20191227_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Disponible'), (2, 'Cancelada')], default=1),
        ),
    ]
