# Generated by Django 2.2.6 on 2019-12-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0005_funcion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Cancelada', 'Cancelada')], default=1, max_length=200),
        ),
    ]
