# Generated by Django 2.2.6 on 2019-12-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0007_auto_20191227_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='funcion',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
